In [81]:
%load_ext autoreload
%autoreload 2
from gymnasium.envs.toy_text.frozen_lake import generate_random_map
import gymnasium as gym
import matplotlib.pyplot as plt
import numpy as np

from rl.dp import Policy, ValueIteration

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Frozen Lake

In [41]:
env = gym.make("FrozenLake-v1", render_mode = "human", desc=generate_random_map(size=8), is_slippery = False)
state, info = env.reset(seed=42)

env.close()

In [42]:
# Initialize policy and policy iterator 
policy : Policy = Policy(env.observation_space.n, env.action_space.n)
vi : ValueIteration = ValueIteration(policy)

In [51]:
episode_count = 1
env = gym.make("FrozenLake-v1", render_mode = "human", desc=generate_random_map(size=8))
state, info = env.reset(seed=42)

policy = vi.forward(env, 1000)
# Print the policy
P = policy.policy
print(np.array(P).reshape(8, 8))

for _ in range(episode_count):
    isStop = False

    state, info = env.reset()

    ctr = 0
    while isStop is False and ctr < 100:
        # Sample from a policy
        action = policy.sample(state)

        state, reward, isTerminated, isTruncated, info = env.step(action)

        if isTerminated or isTruncated:
            isStop = True

        env.render()
        ctr += 1

    state, info = env.reset()

env.close()

[[1 2 3 3 2 2 0 0]
 [1 0 0 0 2 1 0 1]
 [1 3 1 1 1 1 0 0]
 [0 0 2 2 1 1 0 0]
 [0 0 2 3 2 1 3 1]
 [1 1 0 0 2 0 0 2]
 [3 2 0 0 2 0 0 2]
 [0 2 1 1 2 1 1 0]]
[[4.11232638e-02 4.38598825e-02 4.88752198e-02 6.16076970e-02
  8.40677053e-02 8.57917104e-02 8.45151519e-02 4.91483342e-25]
 [4.48797921e-02 4.57697898e-02 2.33461653e-24 9.87657260e-25
  9.56175485e-02 1.00614329e-01 9.65830909e-02 4.47580178e-02]
 [5.10760773e-02 5.57965037e-02 7.93536183e-02 9.95958744e-02
  1.17268119e-01 1.25528819e-01 1.19869754e-01 5.96367744e-24]
 [5.44202947e-02 4.01471019e-24 9.51979955e-02 1.17891550e-01
  1.45195683e-01 1.59268924e-01 1.56424155e-01 7.25799455e-24]
 [6.63571902e-02 8.57879342e-47 1.03380080e-01 1.27497549e-01
  1.81352208e-01 2.01334659e-01 2.14832339e-01 3.20659098e-01]
 [8.87715369e-02 9.72825189e-02 1.03767868e-01 1.37073150e-23
  2.26160840e-01 2.39609115e-01 2.90178633e-23 4.77116240e-01]
 [9.42771133e-02 1.14668550e-01 1.27025404e-01 1.40811520e-23
  2.93230803e-01 3.29164863e-01 3.6

In [40]:
env.close()